*créer une liste de noms;
DATA SAMPLE;
INPUT NAME $ 1-25;
CARDS;
thomas
cruise
mapother
john
ROMAN
MAGGY
;
RUN;

*UPCASE: transformer en majuscules
LOWCASE: transformer en minuscules
PROPCASE: 1ère lettre du mot en majuscule;
DATA CHANGE_CASE;
SET SAMPLE;
UPPER= UPCASE(NAME);
LOWER= LOWCASE(NAME);
PROPER= PROPCASE(NAME);
RUN;

*espace = séparer des valeurs;
DATA NAME_LIST;
    INPUT NAME $ GENDER $;
    DATALINES;
MS.RAJEEV M
MR.JULLY F
MS.MALHOTRA F
MR.KARTIK M
MS.SINHA F
MS.DIVA F
;
RUN;

*TRANWRD & IF THEN ELSE IF THEN ELSE;
DATA SAMPLE2;
SET NAME_LIST;

IF UPCASE(GENDER)= 'M' THEN NAME2= TRANWRD(NAME, "MS", "MR");
ELSE IF UPCASE(GENDER)= 'F' THEN NAME2= TRANWRD(NAME, "MR", "MS");
ELSE NAME2= NAME;

RUN;

PROC PRINT DATA=SAMPLE2;
TITLE 'TRANWRD SELON LE GENRE';
RUN;
