*KEEP= choisir les colonnes, DROP= supprimer les colonnes;
DATA PRICE(KEEP= MODEL TYPE MSRP) FEATURES(DROP= MODEL TYPE MSRP);
SET SASHELP.CARS;
*IF THEN OUTPUT/ ELSE OUTPUT: conditions;
IF MSRP < 19000 THEN OUTPUT PRICE;
ELSE OUTPUT FEATURES;
RUN;

*_N_= index de lignes;
DATA LINE_NUMBER;
SET PRICE;
IF _N_ >= 10 AND _N_ < 20;
RUN;

*OBS= nombre de premières lignes à afficher;
DATA OBSS;
SET PRICE(OBS=15);
RUN;

*FIRSTOBSS: la première ligne à afficher;
DATA FIRSTOBSS;
SET PRICE(OBS=15 FIRSTOBS=7);
RUN;

*INPUT DATALINES: enregistrer des données;
DATA FIRST_DATA;
INPUT EMPLOYEE $6. SALARY;
DATALINES;
SAMuel 1200
ROHAN 4300
LUCAS 500
MICHEL 200
;
RUN;

PROC PRINT DATA=FIRST_DATA;
TITLE 'FIRST_DATA';
RUN;
